- name: configure common utilities for osint image
  become: true
  hosts: localhost
  
  roles:
    - fubarhouse.golang

  go_get:
    - name: golint
      url: github.com/golang/lint/golint


  tasks:

   # - go_get:
   #   - name: golint
   #     url: github.com/golang/lint/golint




    - name: install amass
      snap:
       name: amass
       classic: yes
    - name: install pip3
      apt:
        name: python3-pip
    - name: install curl
      apt:
        name: curl


    - name: libpcap
      apt:
        name: libpcap-dev
    - name: aws-cli
      apt:
        name: awscli


    - name: install pipenv
      apt:
        name: pipenv
    - name: install virtualenv
      apt: 
        name: python3-virtualenv
    - name: clone photon
      git:
        repo: https://github.com/s0md3v/Photon.git
        dest: /apps/photon
    - name: install photon
      pip:
        requirements: /apps/photon/requirements.txt


    - name: install golang
      apt: 
        name: golang-go

 #go_get:
 # - name: naabu
 #   url: github.com/projectdiscovery/naabu/v2/cmd/naabu

    #  naabu (golang)
    #  httpx (golang)
    #  ffuf  (golang)
    #  nuclei (golang)
    #  Eyewitness / GoWitness
    #  photon / gospider / hakrawler
    #  means to pass in secure parameters (VPN & AWS creds)
    #  vpn client (and secure config pull)
    #  AWS/DO instance autocreation / autostart
    #  output paths or bucket
    #  job scripts / query scripts


    
    #- name: clone theHarvester
    #  git: 
    #    repo: https://github.com/laramies/theHarvester.git
    #    dest: /src/theHarvester
    #- name: install theHarvester
    #  pip: 
    #    chdir: /src/theHarvester
    #    requirements: requirements/base.txt

    #- name: install theHarvester
    #  pip: 
    #    name: git+https://github.com/laramies/theHarvester.git
    #    version: 3.1

    #- name: install metagoofil
    #  pip:
    #    name:  git+https://github.com/opsdisk/metagoofil.git
    #- name: install sherlock
    #  pip:
    #    name: git+https://github.com/sherlock-project/sherlock.git
    # - name: install spiderfoot
    #   pip:
    #     name: git+https://github.com/smicallef/spiderfoot.git
    # - name: clone spiderfoot
    #  git: 
    #    repo: https://github.com/smicallef/spiderfoot.git
    #    dest: /apps/spiderfoot
    # - name: install spiderfoot
    #  pip:
    #    requirements: /apps/spiderfoot/requirements.txt