- name: configure common utilities for osint image
  become: true
  hosts: localhost
  
  tasks:
    - name: install visual studio code
      snap: 
        name: code
        classic: yes
    - name: install vlc
      snap: 
        name: vlc
        classic: yes

