- name: configure common utilities for osint image
  become: true
  hosts: localhost
  
  tasks:
    - name: install amass
      snap:
       name: amass
       classic: yes
    - name: install pip3
      apt:
        name: python3-pip
    - name: install curl
      apt:
        name: curl

  
    - name: install pipenv
      apt:
        name: pipenv
    - name: install virtualenv
      apt: 
        name: python3-virtualenv
    - name: clone photon
      git:
        repo: https://github.com/s0md3v/Photon.git
        dest: /apps/photon
    - name: install photon
      pip:
        requirements: /apps/photon/requirements.txt


    - name: install golang
      apt: 
        name: golang-go



    
    #- name: clone theHarvester
    #  git: 
    #    repo: https://github.com/laramies/theHarvester.git
    #    dest: /src/theHarvester
    #- name: install theHarvester
    #  pip: 
    #    chdir: /src/theHarvester
    #    requirements: requirements/base.txt

    #- name: install theHarvester
    #  pip: 
    #    name: git+https://github.com/laramies/theHarvester.git
    #    version: 3.1

    #- name: install metagoofil
    #  pip:
    #    name:  git+https://github.com/opsdisk/metagoofil.git
    #- name: install sherlock
    #  pip:
    #    name: git+https://github.com/sherlock-project/sherlock.git
    # - name: install spiderfoot
    #   pip:
    #     name: git+https://github.com/smicallef/spiderfoot.git
    # - name: clone spiderfoot
    #  git: 
    #    repo: https://github.com/smicallef/spiderfoot.git
    #    dest: /apps/spiderfoot
    # - name: install spiderfoot
    #  pip:
    #    requirements: /apps/spiderfoot/requirements.txt